### ISSUE TITLE
LocationUpdates app can't detect location on device with Android 10 when running with any fake GPS app to mock location

### ISSUE THREAD

**Issue by Dmitry-Komarovsky** [android/location-samples#247]
When I press 'START UPDATES' button in LocationUpdates app while running it with any fake GPS app, I get the following exception:
11-24 19:23:18.876: I/MainActivity(31143): com.google.android.gms.common.api.ResolvableApiException: 6: RESOLUTION_REQUIRED
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:3)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.common.internal.zai.zaf(Unknown Source:2)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.common.internal.zaj.onComplete(Unknown Source:6)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.common.api.internal.BasePendingResult.zaa(Unknown Source:172)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:131)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.setResult(Unknown Source:36)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.internal.location.zzbc.zza(Unknown Source:2)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.internal.location.zzar.dispatchTransaction(Unknown Source:11)
11-24 19:23:18.876: I/MainActivity(31143): 	at com.google.android.gms.internal.location.zzb.onTransact(Unknown Source:22)
11-24 19:23:18.876: I/MainActivity(31143): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
11-24 19:23:18.876: I/MainActivity(31143): 	at android.os.Binder.execTransact(Binder.java:994)

**Comment by DomClaxton** [comment]
I've been finding the same problem. I can't get geofences to trigger with latest Android 11. I haven't tried any other versions. It's very frustrating. Looking at the code for this project it looks outdated but even following the latest Android code recommendations on their website I've not been able to get any Geofences to trigger using the latest Android Studio build emulator.

**Comment by deviant-studio** [comment]
did you guys find any workaround?

**Comment by dominicclaxton** [comment]
> did you guys find any workaround?

No. It seems the Android emulator has an issue with triggering notifications. Or it does on my machine anyway!  It doesn’t work unless you open the maps app. As soon as you do the notifications trigger. 
I can confirm the same code runs perfectly well when running on an actual device. 
I spent quite a few hours thinking my code was at fault. I even tried different Android api’s 26,28,29 and 30. All had the same problem.

**Comment by deviant-studio** [comment]
i have this issue on real devices too. i can confirm that running google maps works as a temporary solution

**Comment by dominicclaxton** [comment]
> i have this issue on real devices too. i can confirm that running google maps works as a temporary solution

So you’re saying that you have to open the maps app on actual device in order for notification go fire?

**Comment by deviant-studio** [comment]
to be precise: this hack doesn't work for real device :( (at least mine xiaomi redmi 9)
but I came to it intuitively when used an emulator. and it worked for me.
