### ISSUE TITLE
Traceback (most recent call last):  File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 951, in <module>    main()  File "/home/marijn/Android/Sdk/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/ndk-gdb.py", line 882, in main    device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)TypeError: can only concatenate list (not "map") to listThis -gdb.py-gdb.pyis another Python 2 -> Python 3 conversion problem just like #1763:

### ISSUE THREAD

**Issue by Gadgetflow7** [android/location-samples#304]
This is another Python 2 -> Python 3 conversion problem just like #1763:

The current code is as follows:

```python
        kill_pids = map(str, kill_pids)
        if kill_pids:
            log("Killing processes: {}".format(", ".join(kill_pids)))
            device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)
```

In Python 2, `map()` returns a list which you can freely concatenate to another list. In Python 3 `map()` returns a lazy `map` object (a generator) and can't be immediately concatenated to a list. Besides, `map()` is discouraged in favour of generator expressions, or in this specific case a list comprehension:

```python
kill_pids = [str(pid) for pid in kill_pids]
```

EDIT: You can however also use `some_list.extend(<iterable, i.e. generator>)` to let the list iterate a generator and append every individual item to itself.

_Originally posted by @MarijnS95 in https://github.com/android/ndk/issues/1764#issuecomment-1242521200_

**Comment by neveruh442** [comment]
>         This is another Python 2 -> Python 3 conversion problem just like #1763:
> 
> The current code is as follows:
> 
> ```python
>         kill_pids = map(str, kill_pids)
>         if kill_pids:
>             log("Killing processes: {}".format(", ".join(kill_pids)))
>             device.shell_nocheck(["run-as", pkg_name, "kill", "-9"] + kill_pids)
> ```
> 
> In Python 2, `map()` returns a list which you can freely concatenate to another list. In Python 3 `map()` returns a lazy `map` object (a generator) and can't be immediately concatenated to a list. Besides, `map()` is discouraged in favour of generator expressions, or in this specific case a list comprehension:
> 
> ```python
> kill_pids = [str(pid) for pid in kill_pids]
> ```
> 
> EDIT: You can however also use `some_list.extend(<iterable, i.e. generator>)` to let the list iterate a generator and append every individual item to itself.
> 
> _Originally posted by @MarijnS95 in https://github.com/android/ndk/issues/1764#issuecomment-1242521200_
>       

```
> `[]()****`
```
